### PR TITLE
Update test-corr.r

### PR DESCRIPTION
**Pull request by jiahuiguo**
The length should be the same as the numbers of all the files, which is 332.

### CODE REVIEW

**Comment by cbryant1000** [comment]
The instructions say, 323?

```
cr <- corr("specdata")
summary(cr)
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
## -1.0000 -0.0528  0.1070  0.1370  0.2780  1.0000
length(cr)
## [1] 323
```

**Comment by cbryant1000** [comment]
JiaHui,

If you take a look at the `complete.R` function, there are 9 cases with zero (0) observations.  In other words, there are 323 complete cases.

**Comment by jiahuiguo** [comment]
I set the threshold as >= threshold, where even if the observation is 0, it will be counted. And yours makes more sense. Thanks.

**Comment by cbryant1000** [comment]
Jason,

You need at least 2 observations of each variable in order to compute the correlation.  And even with 2 observations on each variable, the correlation is perfect +/- 1, so that does not give you much information.  I looked through the `complete.R` output, and there are no data sets with only 1 observation.  The number of observations jumps from the nine 0's to 2 observations per file.

The instructions do say, 'greater than the threshold.'  But, that is an easy mistake to make.  Good luck with the course!  Are you doing the Data Science specialization?

```
> library(boot)
> x <- rnorm(1)
> y <- rnorm(1)
> d <- cbind(x,y)
> d
               x         y
[1,] -0.05630369 0.4728693
> corr(d)
[1] NaN
> x <- rnorm(2)
> y <- rnorm(2)
> d <- cbind(x,y)
> corr(d)
[1] -1
```

**Comment by jiahuiguo** [comment]
Actually I have not decided yet. Anyway, your repo is a great help! Thanks.

**Pull request closed without merging**
